// <auto-generated />
using Gestao_de_Colaboradores_e_Unidades.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Gestao_de_Colaboradores_e_Unidades.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Gestao_de_Colaboradores_e_Unidades.Models.ColaboradoresModel", b =>
                {
                    b.Property<string>("ColaboradorId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ColaboradorNome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("UnidadeId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("ColaboradorId");

                    b.ToTable("Colaboradores");
                });

            modelBuilder.Entity("Gestao_de_Colaboradores_e_Unidades.Models.UnidadesModel", b =>
                {
                    b.Property<string>("UnidadeId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("UnidadeCodigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("UnidadeNome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("UnidadeId");

                    b.HasIndex("UnidadeCodigo")
                        .IsUnique();

                    b.ToTable("Unidades");
                });

            modelBuilder.Entity("Gestao_de_Colaboradores_e_Unidades.Models.UsuariosModel", b =>
                {
                    b.Property<string>("UsuarioId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("UsuarioEmail")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("UsuarioNome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("UsuarioSenha")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<bool>("UsuarioStatus")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("UsuarioId");

                    b.ToTable("Usuarios");
                });
#pragma warning restore 612, 618
        }
    }
}
