// <auto-generated />
using System;
using Gestao_de_Colaboradores_e_Unidades.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Gestao_de_Colaboradores_e_Unidades.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Gestao_de_Colaboradores_e_Unidades.Models.ColaboradoresModel", b =>
                {
                    b.Property<int>("ColaboradorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ColaboradorId"));

                    b.Property<string>("ColaboradorNome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("UnidadeId")
                        .HasColumnType("int");

                    b.HasKey("ColaboradorId");

                    b.HasIndex("UnidadeId");

                    b.ToTable("Colaboradores");
                });

            modelBuilder.Entity("Gestao_de_Colaboradores_e_Unidades.Models.UnidadesModel", b =>
                {
                    b.Property<int>("UnidadeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("UnidadeId"));

                    b.Property<bool>("EstaUnidadeAtiva")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("UnidadeCodigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("UnidadeNome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("UnidadeId");

                    b.HasIndex("UnidadeCodigo")
                        .IsUnique();

                    b.ToTable("Unidades");
                });

            modelBuilder.Entity("Gestao_de_Colaboradores_e_Unidades.Models.UsuariosModel", b =>
                {
                    b.Property<Guid>("UsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("UsuarioEmail")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("UsuarioNome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("UsuarioSenha")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<bool>("UsuarioStatus")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("UsuarioId");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("Gestao_de_Colaboradores_e_Unidades.Models.ColaboradoresModel", b =>
                {
                    b.HasOne("Gestao_de_Colaboradores_e_Unidades.Models.UnidadesModel", "Unidade")
                        .WithMany()
                        .HasForeignKey("UnidadeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Unidade");
                });
#pragma warning restore 612, 618
        }
    }
}
