version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    depends_on:
      - db
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=db;Database=meubanco;User=root;Password=123456;
    networks:
      - minha-rede

  db:
    image: mysql:9.0
    restart: always
    environment:
      MYSQL_DATABASE: meubanco
      MYSQL_USER: root
      MYSQL_PASSWORD: 123456
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - minha-rede

volumes:
  mysql_data:

networks:
  minha-rede:
