
services:
  app:
    build:
      context: ./Gestao
      dockerfile: Dockerfile
    container_name: gestao_app
    depends_on:
      - db
    ports:
      - "5001:5001"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - gestao-network

  db:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 123qwe
      POSTGRES_DB: meubanco2
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - gestao-network

networks:
  gestao-network:
    driver: bridge

volumes:
  db_data: